<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240704212037 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE Table "categories" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE Table "etat_order" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, etat VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE Table "livres" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, isbn VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, image VARCHAR(255) NOT NULL, resume TEXT DEFAULT NULL, editeur VARCHAR(255) NOT NULL, edited_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, prix DOUBLE PRECISION NOT NULL, qte INT NOT NULL, auteur VARCHAR(255) NOT NULL, categorie_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_927187A4BCF5E72D ON livres (categorie_id)');
        $this->addSql('CREATE TABLE "order" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(255) NOT NULL, create_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, etat_payement BOOLEAN NOT NULL, user_id INT NOT NULL, etat_id INT NOT NULL, payement_type_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F5299398AEA34913 ON "order" (reference)');
        $this->addSql('CREATE INDEX IDX_F5299398A76ED395 ON "order" (user_id)');
        $this->addSql('CREATE INDEX IDX_F5299398D5E86FF ON "order" (etat_id)');
        $this->addSql('CREATE INDEX IDX_F5299398BEC4000E ON "order" (payement_type_id)');
        $this->addSql('CREATE Table "order"_details (quantity INT NOT NULL, price INT NOT NULL, orders_id INT NOT NULL, livre_id INT NOT NULL, PRIMARY KEY(orders_id, livre_id))');
        $this->addSql('CREATE INDEX IDX_845CA2C1CFFE9AD6 ON order_details (orders_id)');
        $this->addSql('CREATE INDEX IDX_845CA2C137D925CB ON order_details (livre_id)');
        $this->addSql('CREATE Table "payement_type" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE Table "reset_password_request" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, nom VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, adresse VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE Table "messenger_messages" (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER Table "livres" ADD CONSTRAINT FK_927187A4BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categories (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F5299398A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F5299398D5E86FF FOREIGN KEY (etat_id) REFERENCES etat_order (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F5299398BEC4000E FOREIGN KEY (payement_type_id) REFERENCES payement_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER Table "order"_details ADD CONSTRAINT FK_845CA2C1CFFE9AD6 FOREIGN KEY (orders_id) REFERENCES "order" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER Table "order"_details ADD CONSTRAINT FK_845CA2C137D925CB FOREIGN KEY (livre_id) REFERENCES livres (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER Table "reset_password_request" ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER Table "livres" DROP CONSTRAINT FK_927187A4BCF5E72D');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F5299398A76ED395');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F5299398D5E86FF');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F5299398BEC4000E');
        $this->addSql('ALTER Table "order"_details DROP CONSTRAINT FK_845CA2C1CFFE9AD6');
        $this->addSql('ALTER Table "order"_details DROP CONSTRAINT FK_845CA2C137D925CB');
        $this->addSql('ALTER Table "reset_password_request" DROP CONSTRAINT FK_7CE748AA76ED395');
        $this->addSql('DROP Table "categories"');
        $this->addSql('DROP Table "etat_order"');
        $this->addSql('DROP Table "livres"');
        $this->addSql('DROP TABLE "order"');
        $this->addSql('DROP Table "order"_details');
        $this->addSql('DROP Table "payement_type"');
        $this->addSql('DROP Table "reset_password_request"');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP Table "messenger_messages"');
    }
}
